### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by liuzhihaozhengshuai** [FangXiuwen/Robust_FL#1]
想问下这个代码的环境配置具体是什么呢

**Comment by FangXiuwen** [comment]
感谢对我们工作的关注！我上传了requirements.txt，可以参考一下

**Comment by liuzhihaozhengshuai** [comment]
> 感谢对我们工作的关注！我上传了requirements.txt，可以参考一下

您好，非常感谢您的帮助，但是在requirements.txt文件中出现Pillow==8.2.0 Pillow==9.5.0这导致环境的安装失败，请问pillow应该选择安装哪个版本呢

**Comment by liuzhihaozhengshuai** [comment]
> 感谢对我们工作的关注！我上传了requirements.txt，可以参考一下

在conda的python3.8环境中手动安装了requirements中的相关包，目前已跑通，谢谢你的帮助
