### ISSUE TITLE
请问您的RHFL全局模型怎样全局聚合呢？

### ISSUE THREAD

**Issue by zhangtian-3841** [FangXiuwen/Robust_FL#2]
作者您好！请问经过Collaborative Learning阶段生成的最优局部模型最终怎样聚合成全局模型呢？是通过平均加权吗。
我在论文中没有看到，抱歉打扰您了！

**Comment by FangXiuwen** [comment]
感谢对我们工作的关注！RHFL并没有聚合全局模型这一步。由于模型异构的存在，无法通过简单的梯度加权等策略得到一个包含全局知识的全局模型。因此，RHFL通过对齐不同客户端模型对同一公共数据的预测输出，来实现异构模型联邦学习（论文3.1小节）。

**Comment by zhangtian-3841** [comment]
感谢您为我解答！
